# Generated by Django 4.2 on 2023-04-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_thread_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
